WORK_FLOW_CREATE_SUCCESS_MESSAGE = "Workflow has been created successfully"
INVALID_TASK = "Workflow task must be a JSON array"
WORK_FLOW_ALREADY_EXIST = "Workflow name already exist"
DELETED_STATUS = 0 
RECORD_STATUS = 1
GPT_TYPE_ALREADY_EXIST = "Assistant name already exist"
GPT_TYPE_CREATE_SUCCESS_MESSAGE = "Assistant has been created successfully"
GPT_TYPE_UPDATE_SUCCESS_MESSAGE = "Assistant has been updated successfully"
GPT_TYPE_NOT_FOUND = "Assistant not found"
GPT_TYPE_DELETE_SUCCESS_MESSAGE = "Assistant deleted successfully"
MODEL_GPT_TURBO = "gpt-4"
MODEL_DALLE_GPT = "dall-e-3"
IMAGE_SIZE = "1024x1024"
IMAGE_QUALITY = "standard"
NUMBER_OF_IMAGES = 1
GPT_ERROR_MESSAGE = "Sorry, I couldn't understand that. Please provide more context or try rephrasing your request."
GPT_TYPE_EXIST_IN_WORKFLOW = "  This Assistant is being used in the following Workflow(s)     "
IMAGE_SAVING_PATH = '/plugins/static/img/dalle_response'
IMAGE_RETREIVING_PATH = 'static/main/img/dalle_response'
ENABLED_STATUS = 1
CHANGE_DELETED_STATUS=1
CLIENT_ADMIN_ROLE="Client Admin"
DEFAULT_ROLE="Default User"
WORK_FLOW_NOT_FOUND = "Workflow not found"
GPT_TYPE_NOT_EXIST_IN_WORKFLOW = "This Assistant is not used in any workflows."